kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.application.name}}
  {{- with .Values.namespace.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.namespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}