kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ .Values.application.name }}-azurefile"
provisioner: file.csi.azure.com # replace with "kubernetes.io/azure-file" if aks version is less than 1.21
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=30
parameters:
  skuName: "{{ .Values.storageclass.sku }}"
  protocol: "{{ .Values.storageclass.protocol }}"
  networkEndpointType: "{{ .Values.storageclass.networkEndpointType }}"
  allowBlobPublicAccess: "false"
  storeAccountKey: "{{ .Values.storageclass.storeAccountKey }}"
  secretName: "{{ .Values.storageclass.secretName }}"
  secretNamespace: "{{ .Values.application.name }}"
  shareName: "{{ .Values.application.name }}-share"
  resourceGroup: "{{ .Values.storageclass.resourceGroup }}"